### ISSUE TITLE
Query Selector All error

### ISSUE THREAD

**Issue by slimeygecko** [mobify/bellows#51] opened 2014-12-09 05:56 UTC
When I tried replicating the demo, I get this error:

    Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Element': '> .bellows__item > .bellows__content' is not a valid selector.zepto.min.js:2 T.qsazepto.min.js:2 n.fn.findbellows.js:59 Bellows._initbellows.js:37 Bellowsbellows.js:217 (anonymous function)zepto.min.js:2 (anonymous function)zepto.min.js:2 n.fn.eachbellows.js:206 $.fn.bellows(index):44 (anonymous function)

**Comment by IrisClasson** [comment] 2015-01-07 09:49
I'm getting the same error replicating the demo

**Comment by IrisClasson** [comment] 2015-01-07 09:55
Some quick debugging shows the problem is somewhere here in bellows:

```javascript
_wrapContent: function($items) {
            $items
                .find(selectors.ITEM_CONTENT)
                // wrap content section of each item to facilitate padding
                .wrap('<div class="bellows__content-wrapper" />')
                // add aria-hidden attribute to all hidden content wrappers
                .parents('.bellows__item:not(.bellows--is-open)')
                .find(selectors.ITEM_CONTENT_WRAPPER)
                .attr('aria-hidden', true);
        }
```
In zepto it then produces the error on this line:
```javascript
else if (this.length == 1) result = $(zepto.qsa(this[0], selector))
```

**Comment by scalvert** [comment] 2015-01-07 18:05
So if you run `grunt serve`, and view the examples page at `http://localhost:3000/examples/index.html`, is the problem reproducible? 

I should note that Bellows is built off a custom version of Zepto. Not custom in the sense that we hacked it, but custom built. In the lib folder of the repo you will find the custom build, which includes Zepto with a number of other modules built into it.

**Comment by scalvert** [comment] 2015-02-02 17:04
Since I haven't been able to reproduce this, I'm going to close for now. Feel free to reopen if it's legit!

**Comment by drwlrsn** [comment] 2015-02-06 00:00
I get the same error. I am not doing anything exciting.
Here is what bower has installed:
```
├─┬ bellows#5.0.0 extraneous
│ ├── mobify-velocity#1.1.2
│ ├─┬ plugin#3.0.0
│ │ ├── requirejs#2.1.15
│ │ └── requirejs-text#2.0.13
│ ├── requirejs#2.1.15
│ └── requirejs-text#2.0.13
├── react#0.12.2 extraneous
└── zepto#1.1.6 extraneous
```
Here is what my JS looks like:
`$(".bellows").bellows();`

Now that we have that out of the way. As @slimeygecko mentions `document.querySelectorAll()` is trying to [execute](https://github.com/mobify/bellows/blob/master/src/js/bellows.js#L123) that [CSS selector](https://github.com/mobify/bellows/blob/master/src/js/bellows.js#L25). 

You can verify that this is not a valid query by running `document.querySelectorAll('> .bellows__item > .bellows__content')` in your favourite JS console. However this query [will work with jQuery](http://stackoverflow.com/questions/17957647/why-is-this-expression-illegal-in-queryselectorall).

At first I thought you might be chaining `selectors` properties, but it appears you aren't. So changing to use valid selectors will fix this bad boy up.

**Comment by drwlrsn** [comment] 2015-02-09 23:42
I think one could call this maybe a documentation problem. Right now it's not clear from the documentation that Bellows requires more than just the default Zepto build. It requires the following modules: *selector*, *stack*, and *data*. Which is totally fine since the *selector* module is like 3kb. Maybe point to [Zepto Builder](http://github.e-sites.nl/zeptobuilder/) so it's fairly straight forward download.

However I still think those [selectors](https://github.com/mobify/bellows/blob/master/src/js/bellows.js#L22-L25) are [gnarly](http://www.w3.org/TR/css3-selectors/#child-combinators) and needlessly disregard [CSS3 grammar](http://www.w3.org/TR/css3-selectors/#grammar).

If those selectors are changed, then Bellows itself no longer relies on the *selector* module, and only the unit tests use some of its functions. 

¯\_(ツ)_/¯

**Comment by kpeatt** [comment] 2015-02-10 18:10
@drwlrsn Thanks for the feedback! I agree that it makes sense to try to find a way to remove our need for the selector module. In the short term, I'll probably go the documentation route.

Would you be willing to let us know what project you're looking at using Bellows for? I'm always curious about how people are using our things.

**Comment by scalvert** [comment] 2015-02-11 04:59
@drwlrsn thanks for the feedback! Agree this was an omission in the documentation! 

In the short term, we're looking to move permanently to jQuery, so this should all be a moot point!

**Comment by drwlrsn** [comment] 2015-02-11 22:32
@kpeatt I am building a box office web app for a local theatre production company in town. Nothing too exciting I am afraid.

**Comment by ericmuyser** [comment] 2015-02-12 00:56
@drwlrsn That sounds exciting to me!

**Comment by kpeatt** [comment] 2015-02-12 05:52
@drwlrsn Would love to see it when you're done!

**Comment by donnielrt** [comment] 2015-05-22 18:07
Seems like this issue's been resolved closing!

**Closed by donnielrt** 2015-05-22 18:07 UTC
Labels: enhancement, question
